version: "3.7"
services:
  controllers:
      image: distortedlogic/controllers:latest
      build: .
      container_name: controllers
      restart: on-failure
      volumes:
        - .:/app
      ports:
        - 8001:8000
  controller-tasks:
    image: distortedlogic/controllers:latest
    container_name: controller-tasks
    restart: on-failure
    command: celery -A controller.CELERY worker -B -l info
    volumes:
      - .:/app