FROM python:3.7.6-buster as builder
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

FROM python:3.7.6-slim
RUN apt-get update \
  && apt-get install -qq -y \
  build-essential libpq-dev tesseract-ocr python3-setuptools \
  --no-install-recommends
COPY --from=builder /usr/local/lib/python3.7/site-packages /usr/local/lib/python3.7/
COPY --from=builder /app .
COPY . .
RUN pip install --editable .
CMD gunicorn -c "python:config.gunicorn" "controller:APP"