version: 2.1
jobs:
  build-and-deploy:
    docker:
      - image: python:3.7.6-buster
      - image: postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
      - image: redislabs/redismod:latest
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "requirements.txt"}}
            - v1-dependencies-
      - run:
          name: Install Python deps
          command: pip install -r requirements.txt
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{checksum "requirements.txt"}}
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Install Docker Client
          command: |
            set -x
            VER="18.06.3-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build Backend Docker Image
          command: docker build
            --build-arg POSTGRES_USER=$POSTGRES_USER
            --build-arg POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            --build-arg POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            -f Dockerfile.prod
            -t distortedlogic/controllers:latest .
      - run: docker login -u distortedlogic -p $DOCKERHUB_TOKEN
      - run: docker push distortedlogic/controllers:latest

workflows:
  build-docker-image-only:
    jobs:
      - build-and-deploy:
          context:
            - dockerhub
            - shared