version: 2.1
jobs:
  build-and-deploy:
    docker:
      - image: python:3.8.6-buster
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Install Docker Client
          command: |
            set -x
            VER="18.06.3-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build Backend Docker Image
          command: docker build
            -f Dockerfile.prod
            -t distortedlogic/flask:latest .
      - run: docker login -u distortedlogic -p $DOCKERHUB_TOKEN
      - run: docker push distortedlogic/flask:latest
      - run:
          name: Build Backend Docker Image
          command: docker build
            -f Dockerfile.jupyter.prod
            -t distortedlogic/jupyter:latest .
      - run: docker push distortedlogic/jupyter:latest

workflows:
  build-docker-image-only:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - master
          context:
            - dockerhub
            - shared