version: 2
jobs:
  build:
    docker:
      - image: python:3.7.6-buster
      - image: postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
      - image: redislabs/redismod:latest
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "requirements.txt"}}
            - v1-dependencies-
      - run:
          name: Install Python deps
          command: pip install -r requirements.txt
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{checksum "requirements.txt"}}
      - run: npm run build
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Install Docker Client
          command: |
            set -x
            VER="18.06.3-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build Backend Docker Image
          command: docker build --build-arg CORS_ORIGIN=$CORS_ORIGIN
            --build-arg HIVE_ACCOUNT=$HIVE_ACCOUNT
            --build-arg ACTIVE_WIF=$ACTIVE_WIF
            --build-arg RC_THRESHOLD=$RC_THRESHOLD
            --build-arg AWS_ID=$AWS_ID
            --build-arg AWS_KEY=$AWS_KEY
            --build-arg SECRET=$SECRET
            -f Dockerfile.prod -t dokku/controllers:latest .
      - run: docker save dokku/backend:latest | bzip2 | ssh  -o StrictHostKeyChecking=no ubuntu@ec2-3-236-121-24.compute-1.amazonaws.com \"bunzip2 | docker load\"
      - run: ssh  -o StrictHostKeyChecking=no ubuntu@ec2-3-236-121-24.compute-1.amazonaws.com \"dokku tags:deploy controllers latest\"