version: 2.1
jobs:
  build-and-deploy:
    docker:
      - image: python:3.7.6-buster
      - image: postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
      - image: redislabs/redismod:latest
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "requirements.txt"}}
            - v1-dependencies-
      - run:
          name: Install Python deps
          command: pip install -r requirements.txt
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{checksum "requirements.txt"}}
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Install Docker Client
          command: |
            set -x
            VER="18.06.3-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build Backend Docker Image
          command: docker build
            --build-arg SECRET_KEY=$SECRET_KEY
            --build-arg FLASK_ENV=$FLASK_ENV
            --build-arg reddit_oauth_0=$reddit_oauth_0
            --build-arg reddit_oauth_1=$reddit_oauth_1
            --build-arg reddit_oauth_2=$reddit_oauth_2
            --build-arg reddit_oauth_3=$reddit_oauth_3
            --build-arg reddit_oauth_4=$reddit_oauth_4
            --build-arg reddit_oauth_5=$reddit_oauth_5
            --build-arg reddit_oauth_6=$reddit_oauth_6
            --build-arg reddit_oauth_7=$reddit_oauth_7
            -f Dockerfile.prod
            -t distortedlogic/flask:latest .
      - run: docker login -u distortedlogic -p $DOCKERHUB_TOKEN
      - run: docker push distortedlogic/flask:latest

workflows:
  build-docker-image-only:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - master
          context:
            - dockerhub
            - shared