"""quick_fix

Revision ID: 4a2537d0ef82
Revises: c0d038ed9891
Create Date: 2021-03-17 16:43:53.361661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2537d0ef82'
down_revision = 'c0d038ed9891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
