"""quick_fix_name

Revision ID: c7546e52ff98
Revises: 4a2537d0ef82
Create Date: 2021-03-17 16:45:48.933523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7546e52ff98'
down_revision = '4a2537d0ef82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('not_a_meme_test', 'name')
    op.drop_column('not_a_meme_train', 'name')
    op.drop_column('not_a_template_test', 'name')
    op.drop_column('not_a_template_train', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('not_a_template_train', sa.Column('name', sa.VARCHAR(length=400), autoincrement=False, nullable=False))
    op.add_column('not_a_template_test', sa.Column('name', sa.VARCHAR(length=400), autoincrement=False, nullable=False))
    op.add_column('not_a_meme_train', sa.Column('name', sa.VARCHAR(length=400), autoincrement=False, nullable=False))
    op.add_column('not_a_meme_test', sa.Column('name', sa.VARCHAR(length=400), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
